### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by jlarmstrongiv** [mbeissinger/tfjs-converter#1]
When first trying to run the conversion script:
```
python src/lobe_tf_to_tfjs.py ./model/saved_model.pb
Traceback (most recent call last):
  File "src/lobe_tf_to_tfjs.py", line 7, in <module>
    from src.savedmodel_to_tfjs import convert_savedmodel
ModuleNotFoundError: No module named 'src'
```
I switched this [line](https://github.com/mbeissinger/tfjs-converter/blob/main/src/lobe_tf_to_tfjs.py#L7) inside `lobe_tf_to_tfjs.py` to:
```python
from savedmodel_to_tfjs import convert_savedmodel
```
With that hotfix, the model compiles!  Albeit with quite a few warnings haha

I don’t regularly code python, so I’m unsure if that’s the right and final fix.

**Comment by mbeissinger** [comment]
What directory were you running the script from? Generally if you run into that ModuleNotFoundError, you can also try running the script with the module flag like so: `python -m src.lobe_tf_to_tfjs path/to/exported/model --output_dir=path/to/desired/output`

Does that command line work as well?

**Comment by mwoof** [comment]
I have been getting the same No module named "src" issue with both  `python -m src.lobe_tf_to_tfjs path/to/exported/model --output_dir=path/to/desired/output` and `python src.lobe_tf_to_tfjs path/to/exported/model --output_dir=path/to/desired/output`

jlarmstrongiv `from savedmodel_to_tfjs import convert_savedmodel` seems to have worked for me as well... with a lot of warnings.

**Comment by jlarmstrongiv** [comment]
I tried to reproduce, but got this error instead #2

**Comment by jlarmstrongiv** [comment]
After git cloning and installing from scratch, running `python -m src.lobe_tf_to_tfjs path/to/exported/model` worked without errors 👍
