### ISSUE TITLE
ERROR: ResolutionImpossible

### ISSUE THREAD

**Issue by jlarmstrongiv** [mbeissinger/tfjs-converter#2]
pip install -r requirements.txt

Collecting tensorflow==1.15.4
  Using cached tensorflow-1.15.4-cp37-cp37m-macosx_10_9_x86_64.whl (123.3 MB)
Collecting tensorflowjs==2.7.0
  Using cached tensorflowjs-2.7.0-py3-none-any.whl (62 kB)
INFO: pip is looking at multiple versions of tensorflow to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 2) and tensorflow==1.15.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested tensorflow==1.15.4
    tensorflowjs 2.7.0 depends on tensorflow<3 and >=2.1.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by mbeissinger** [comment]
What OS and pip/python version are you running? For me with Windows 10 and Python 3.7/pip 20.1.1 it shows an error but installs anyway (which is fine to ignore that error). A workaround could be installing first the tensorflowjs==2.7.0 requirement, then in a separate pip install tensorflow==1.15.4

**Comment by jlarmstrongiv** [comment]
MacOS Catalina, Python 3.7, pip-20.3.1

That workaround was successful 🎉

I feel like I may have done that the first time, but forgot about it 😂
